Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: deploy-cloudwatch-alarms-extra
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - sns:Get*
            - sns:List*
            - sns:CreateTopic
            - sns:DeleteTopic
            - sns:SetTopicAttributes
            - cloudwatch:PutMetricAlarm
            - cloudwatch:DeleteAlarms
            - cloudwatch:ListMetrics
            # - cloudwatch:DescribeAlarmsForMetric
            - cloudwatch:DescribeAlarms* 
            Resource: '*'
            Effect: Allow