Parameters:
  DatabaseAlarmMaxCpuPercent:
    Description: Database CPU % max for alarm
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 99
    ConstraintDescription: Must be a percentage between 1-99%

  DatabaseAlarmReadLatencyMaxSeconds:
    Description: Read latency max for alarm
    Type: Number
    Default: 1
    MinValue: 1

  DatabaseAlarmWriteLatencyMaxSeconds:
    Description: Write latency max for alarm
    Type: Number
    Default: 1
    MinValue: 1

  DatabaseAlarmEvaluationPeriods:
    Description: The number of periods over which data is compared to the specified threshold
    Type: Number
    Default: 2
    MinValue: 2

  DatabaseAlarmEvaluationPeriodSeconds:
    Description: The time over which the specified statistic is applied. Specify time in seconds, in multiples of 60. Enhanced monitoring must be enabled if less than 500 seconds
    Type: Number
    Default: 300
    MinValue: 60
    ConstraintDescription: Must be at least 60 seconds
  
  # Default is 200 MB
  DatabaseAlarmSwapUsageInBytes:
    Default: 209715200
    Type: Number
    Description: Number of swap usage bytes for alarm (if enabled)
    MinValue: 1
    ConstraintDescription: A value of one byte or more
  
  # Default is 500 MB
  DatabaseAlarmMinFreeSpaceInBytes:
    Default: 524288000
    Type: Number
    Description: Number of min free space bytes for alarm (if enabled)
    MinValue: 1
    ConstraintDescription: A value of one byte or more

  EnableDatabaseAlarms:
    Default: false
    Type: String
    Description: Set to true to enable (additional charges - https://aws.amazon.com/cloudwatch/pricing/)
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

Conditions:
  AlarmsEnabled: 
    Fn::Equals: 
      - Ref: EnableDatabaseAlarms
      - true 

Resources:

  DatabaseAlarmTopic:
    Type: AWS::SNS::Topic
    Condition: AlarmsEnabled
    Properties:
      DisplayName: 
        Fn::Sub: "${DatabaseName} Database Alarm Topic"

  DatabaseCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmName: 
        Fn::Sub: "[${Namespace}-${DatabaseEngine}-${EnvironmentName}] DB CPU utilization"
      AlarmDescription: !Sub "DB CPU utilization is over ${DatabaseAlarmMaxCpuPercent}% for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds"
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      EvaluationPeriods: 
        Ref: DatabaseAlarmEvaluationPeriods
      Period: 
        Ref: DatabaseAlarmEvaluationPeriodSeconds
      Threshold: 
        Ref: DatabaseAlarmMaxCpuPercent
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: 
            Fn::If:
            - IsClustered
            - Ref: DBCluster
            - Ref: DBInstanceStandalone
      AlarmActions:
        - Ref: DatabaseAlarmTopic

  DatabaseFreeStorageSpaceAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmName: 
        Fn::Sub: "[${Namespace}-${DatabaseEngine}-${EnvironmentName}] DB free storage space"
      AlarmDescription: !Sub "DB free storage space is less than ${DatabaseAlarmMinFreeSpaceInBytes} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds"
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: FreeStorageSpace
      Unit: Bytes
      Statistic: Average
      EvaluationPeriods: 
        Ref: DatabaseAlarmEvaluationPeriods
      Period: 
        Ref: DatabaseAlarmEvaluationPeriodSeconds
      Threshold: 
        Ref: DatabaseAlarmMinFreeSpaceInBytes
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::If:
            - IsClustered
            - Ref: DBCluster
            - Ref: DBInstanceStandalone
      AlarmActions:
        - Ref: DatabaseAlarmTopic

  DatabaseSwapUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmName: 
        Fn::Sub: "[${Namespace}-${DatabaseEngine}-${EnvironmentName}] DB swap usage"
      AlarmDescription: !Sub "DB swap usage is greater than than ${DatabaseAlarmSwapUsageInBytes} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds"
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: SwapUsage
      Unit: Bytes
      Statistic: Average
      EvaluationPeriods: 
        Ref: DatabaseAlarmEvaluationPeriods
      Period: 
        Ref: DatabaseAlarmEvaluationPeriodSeconds
      Threshold: 
        Ref: DatabaseAlarmSwapUsageInBytes
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::If:
            - IsClustered
            - Ref: DBCluster
            - Ref: DBInstanceStandalone
      AlarmActions:
        - Ref: DatabaseAlarmTopic

  DatabaseReadLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmName: 
        Fn::Sub: "[${Namespace}-${DatabaseEngine}-${EnvironmentName}] DB read latency"
      AlarmDescription: !Sub "DB read latency is over ${DatabaseAlarmReadLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds"
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: ReadLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: 
        Ref: DatabaseAlarmEvaluationPeriods
      Period: 
        Ref: DatabaseAlarmEvaluationPeriodSeconds
      Threshold: 
        Ref: DatabaseAlarmReadLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::If:
            - IsClustered
            - Ref: DBCluster
            - Ref: DBInstanceStandalone
      AlarmActions:
        - Ref: DatabaseAlarmTopic

  DatabaseWriteLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmName: 
        Fn::Sub: "[${Namespace}-${DatabaseEngine}-${EnvironmentName}] DB write latency"
      AlarmDescription: !Sub "DB write latency is over ${DatabaseAlarmWriteLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds"
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: WriteLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: 
        Ref: DatabaseAlarmEvaluationPeriods
      Period: 
        Ref: DatabaseAlarmEvaluationPeriodSeconds
      Threshold: 
        Ref: DatabaseAlarmWriteLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::If:
            - IsClustered
            - Ref: DBCluster
            - Ref: DBInstanceStandalone
      AlarmActions:
        - Ref: DatabaseAlarmTopic

Outputs:
  DatabaseAlarmTopicArn:
    Description: Database Alarm Topic ARN
    Condition: AlarmsEnabled
    Value: !Ref DatabaseAlarmTopic
    Export:
      Name: 
        Fn::Sub: "${AWS::StackName}-DatabaseAlarmTopicArn"

  DatabaseAlarmTopicName:
    Description: Database Alarm Topic Name
    Condition: AlarmsEnabled
    Value: !GetAtt DatabaseAlarmTopic.TopicName
    Export:
      Name: 
        Fn::Sub: "${AWS::StackName}-DatabaseAlarmTopicName"