Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: deploy-database-extra
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - sns:CreateTopic
            Resource: '*'
            Effect: Allow