Resources:
#   ElbSG:
#     Type: AWS::EC2::SecurityGroup
#     Properties:
#       GroupDescription: ELB Security Group
#       SecurityGroupIngress:
#       - IpProtocol: tcp
#         FromPort: '80'
#         ToPort: '80'
#         CidrIp: 62.96.159.233/32
#       - IpProtocol: tcp
#         FromPort: '443'
#         ToPort: '443'
#         CidrIp: 62.96.159.233/32
  Host2ELB80RuleIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 62.96.159.233/32
      GroupId: 
        Ref: ElbSG
  Host2ELB443RuleIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      CidrIp: 62.96.159.233/32
      GroupId: 
        Ref: ElbSG