# Accomadates https://github.com/stelligent/mu/blob/develop/templates/assets/cloudformation/service-iam.yml

Resources:
  # Add additional AWS::IAM::Role elements to EcsTaskRole
  EcsTaskRole:
    Type: AWS::IAM::Role
    Condition: IsEcsService
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      # S3 access policy
      - PolicyName: s3-access
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - "s3:Get*"
            - "s3:Put*"
            Resource: '*'
